In [2]:
import numpy as np
import pandas as pd

Read the CSV file and remove the last row from dataframe because the last row is the captured ACUBA scores for this dataset.

In [3]:
df=pd.read_csv("RESULTS_EUROVIS2015.csv");

AUC_scores=df.tail(1);
main_df=df[:-1];

print("Total number of rows in original dataframe:"+str(len(df.index)));
print("Total number of rows in modified dataframe:"+str(len(main_df.index)));

Total number of rows in original dataframe:829
Total number of rows in modified dataframe:828

In [4]:
main_df.describe()

,indexFile,indexDR,classNum,scoreA,scoreM,scoreDes,DSC,CAL,HM,LDA,...,DC 20%,HDM 80,DC 2%,DUNN,DC 1%,DC 0.5%,CDM 1,DC 0.2%,DC 0.1%,AWTN
count,828.000000,828.000000,828.00000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,...,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000
mean,37.751208,2.450483,3.52657,2.979469,2.949275,0.507246,77.429402,80.298799,82.342098,0.594322,...,63.634851,98.403195,96.553164,0.027152,99.459394,99.935704,87.927730,99.996095,99.999158,270.766188
std,20.766822,1.115446,2.54403,1.631259,1.749717,0.500250,14.363301,118.300177,10.342507,1.481028,...,19.729777,3.748677,4.953790,0.059874,1.121827,0.185837,7.215781,0.019771,0.005084,78.268813
min,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000,29.010239,0.007398,47.360794,0.000002,...,5.374185,53.901868,57.287289,0.000891,87.332331,97.799476,39.832298,99.711761,99.925354,38.993885
25%,16.000000,1.000000,2.00000,1.000000,1.000000,0.000000,66.650000,3.798646,75.515331,0.012565,...,52.270991,98.247322,95.165531,0.003489,99.374314,99.944297,84.619306,99.999112,100.000000,235.497898
50%,40.000000,3.000000,3.00000,3.000000,3.000000,1.000000,79.335260,24.730365,83.765962,0.091180,...,64.001399,100.000000,98.675758,0.007414,99.875350,99.992992,89.100684,100.000000,100.000000,286.045767
75%,55.000000,3.000000,5.00000,5.000000,5.000000,1.000000,89.450000,113.261177,90.789427,0.533361,...,76.557142,100.000000,99.852436,0.026669,100.000000,100.000000,92.874167,100.000000,100.000000,324.972774
max,70.000000,4.000000,13.00000,5.000000,5.000000,1.000000,100.000000,1038.602336,99.005716,25.837629,...,100.000000,100.000000,100.000000,0.707247,100.000000,100.000000,99.310559,100.000000,100.000000,457.396744

In [5]:
main_df.columns

Index(['fileName', 'indexFile', 'indexDR', 'classNum', 'scoreA', 'scoreM',
       'scoreDes', 'DSC', 'CAL', 'HM', 'LDA', 'WII', 'SIL', 'GAM', 'ABW', 'CS',
       'HDM 10', 'ABTN', 'HDM 5', 'CDM 4', 'CDM 3', 'DC 10%', 'CDM 5', 'CDM 2',
       'CDM 6', 'CDM 7', 'DC 5%', 'CDM 8', 'CDM 10', 'CDM 9', 'HDM 20',
       'HDM 40', 'DC 20%', 'HDM 80', 'DC 2%', 'DUNN', 'DC 1%', 'DC 0.5%',
       'CDM 1', 'DC 0.2%', 'DC 0.1%', 'AWTN'],
      dtype='object')

In [6]:
#rerranging the columms in the order given in the paper.
target_var='scoreDes'
file_descriptors=['fileName', 'indexFile', 'indexDR', 'classNum', 'scoreA', 'scoreM']+[target_var]


measure_cols=['ABTN','AWTN','ABW','WII','CAL','LDA','DUNN','GAM','SIL','HM','CS','DSC',
            'CDM 1','CDM 2','CDM 3','CDM 4','CDM 5', 'CDM 6', 'CDM 7', 'CDM 8', 'CDM 9', 'CDM 10',
           'DC 0.1%','DC 0.2%','DC 0.5%','DC 1%','DC 2%','DC 5%','DC 10%','DC 20%',
           'HDM 5','HDM 10','HDM 20','HDM 40','HDM 80']

new_cols=file_descriptors+measure_cols;

In [7]:
main_df=main_df[new_cols]
print(main_df.columns);

Index(['fileName', 'indexFile', 'indexDR', 'classNum', 'scoreA', 'scoreM',
       'scoreDes', 'ABTN', 'AWTN', 'ABW', 'WII', 'CAL', 'LDA', 'DUNN', 'GAM',
       'SIL', 'HM', 'CS', 'DSC', 'CDM 1', 'CDM 2', 'CDM 3', 'CDM 4', 'CDM 5',
       'CDM 6', 'CDM 7', 'CDM 8', 'CDM 9', 'CDM 10', 'DC 0.1%', 'DC 0.2%',
       'DC 0.5%', 'DC 1%', 'DC 2%', 'DC 5%', 'DC 10%', 'DC 20%', 'HDM 5',
       'HDM 10', 'HDM 20', 'HDM 40', 'HDM 80'],
      dtype='object')

In [8]:
main_df.describe()

,indexFile,indexDR,classNum,scoreA,scoreM,scoreDes,ABTN,AWTN,ABW,WII,...,DC 1%,DC 2%,DC 5%,DC 10%,DC 20%,HDM 5,HDM 10,HDM 20,HDM 40,HDM 80
count,828.000000,828.000000,828.00000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,...,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000,828.000000
mean,37.751208,2.450483,3.52657,2.979469,2.949275,0.507246,338.962642,270.766188,1.319842,0.319472,...,99.459394,96.553164,85.741579,74.872428,63.634851,71.313912,80.529741,89.152458,95.264410,98.403195
std,20.766822,1.115446,2.54403,1.631259,1.749717,0.500250,111.231871,78.268813,0.629271,0.289950,...,1.121827,4.953790,13.214279,17.521521,19.729777,19.202670,16.130626,12.025008,6.933171,3.748677
min,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000,49.310536,38.993885,0.600845,-3.527704,...,87.332331,57.287289,21.619166,10.517643,5.374185,3.658876,12.357476,31.797620,51.107174,53.901868
25%,16.000000,1.000000,2.00000,1.000000,1.000000,0.000000,275.088871,235.497898,1.015355,0.253168,...,99.374314,95.165531,79.880495,66.123959,52.270991,60.522081,72.438332,84.133503,93.066142,98.247322
50%,40.000000,3.000000,3.00000,3.000000,3.000000,1.000000,350.604171,286.045767,1.209355,0.372944,...,99.875350,98.675758,88.616953,76.929400,64.001399,72.610273,83.561170,92.835117,97.952218,100.000000
75%,55.000000,3.000000,5.00000,5.000000,5.000000,1.000000,401.936194,324.972774,1.431921,0.474543,...,100.000000,99.852436,95.800770,87.248803,76.557142,85.641875,93.738713,98.802395,100.000000,100.000000
max,70.000000,4.000000,13.00000,5.000000,5.000000,1.000000,939.229710,457.396744,9.333784,0.645071,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [9]:
main_df['scoreDes'].value_counts()

1    420
0    408
Name: scoreDes, dtype: int64